image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - replace
  - deploy

maven-test-jdk-8:
  image: maven:3-jdk-8
  stage: build
  script: "./mvnw package -B"
  artifacts:
    paths:
      - target/*.war

docker-build-dev:
  stage: package
  script:
  - docker build -t magoo-dev/spring-pet-clinic-dev .
  only:
  - develop

docker-replace-dev:
  allow_failure: true
  stage: replace
  script:
  - docker stop pclinic-latest-dev
  only:
  - develop
  
docker-deploy-dev:
  stage: deploy
  script:
  - docker run -d --name pclinic-latest-dev --rm -p 8011:8080 magoo-dev/spring-pet-clinic-dev
  environment:
    name: DEV
    url: http://localhost:8011/petclinic/
  only:
  - develop

docker-build-uat:
  stage: package
  script:
  - docker build -t magoo-dev/spring-pet-clinic-uat .
  only:
  - master
  
docker-replace-uat:
  allow_failure: true
  stage: replace
  script:
  - docker stop pclinic-latest-uat
  only:
  - master

docker-deploy-uat:
  stage: deploy
  script:
  - docker run -d --name pclinic-latest-uat --rm -p 8012:8080 magoo-dev/spring-pet-clinic-uat
  environment:
    name: UAT
    url: http://localhost:8012/petclinic/
  only:
  - master
