image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - replace
  - deploy

maven-test-jdk-8:
  image: maven:3-jdk-8
  stage: build
  script: "./mvnw package -B"
  artifacts:
    paths:
      - target/*.war
      
maven-test-jdk-9:
  image: maven:3-jdk-9
  stage: build
  script: "./mvnw package -B"
  artifacts:
    paths:
      - target/*.war

docker-build-dev:
  stage: package
  script:
  - docker build -t magoo-dev/spring-pet-clinic-dev .

docker-replace-dev:
  allow_failure: true
  stage: replace
  script:
  - docker stop pclinic-latest-dev
  
docker-deploy-dev:
  stage: deploy
  script:
  - docker run -d --name pclinic-latest-dev --rm -p 8011:8080 magoo-dev/spring-pet-clinic-dev
  environment:
    name: DEV
